version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-1234}:${PORT:-8000}"
    environment:
      PORT: ${PORT:-8000}
    volumes:
      - ~/Pictures/test/:/images
    restart: unless-stopped
