version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      PORT: 8000
      IMAGE_DIR: /images
    volumes:
      - ~/Pictures/test/:/images
    restart: unless-stopped
